import type { Metadata } from "next";
import { JsonLd } from "@/components/JsonLd";
import { absoluteUrl } from "@/lib/site";

const title = "How to Start an Interactive Story You Actually Want to Finish";
const description = "Choose a character, enter a specific opening moment, and use small decisions to create an interactive story with momentum.";
export const metadata: Metadata = { title, description, alternates: { canonical: "/blog/start-an-interactive-story" }, openGraph: { type: "article", title, description, url: "/blog/start-an-interactive-story" } };

export default function StartInteractiveStoryPost() {
  return <main style={S.wrap}><JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "ReverieTale" }, mainEntityOfPage: absoluteUrl("/blog/start-an-interactive-story") }} /><a href="/blog" style={S.back}>Journal</a><p style={S.eyebrow}>Interactive fiction</p><h1 style={S.title}>{title}</h1><p style={S.deck}>The best interactive stories do not begin with a blank page. They begin with a clear moment you want to see through.</p><article style={S.article}><h2>Start with a moment, not a biography</h2><p>Pick the companion whose point of view feels interesting, then open a scene with a little pressure already in the air: a missed train, a strange voicemail, an unfinished song, or a map with one detail that does not belong.</p><h2>Give yourself one useful choice</h2><p>Early decisions work best when they are concrete. Ask a question, follow a clue, change the setting, or tell the character what you notice. A small action creates more momentum than trying to outline the whole story at once.</p><h2>Let the conversation continue the scene</h2><p>When an opening chapter ends, you can keep talking with the character in the same story context. Use the chat to test an idea, learn what they are hiding, or decide what happens when the next chapter begins.</p><p><a href="/browse" style={S.cta}>Explore companions</a></p></article></main>;
}

const S: Record<string, React.CSSProperties> = { wrap: { maxWidth: 740, margin: "0 auto", padding: "54px 24px 88px" }, back: { color: "#E9A06B", fontSize: 13.5, fontWeight: 700, textDecoration: "none" }, eyebrow: { color: "#E9A06B", fontSize: 12, letterSpacing: ".18em", textTransform: "uppercase", fontWeight: 700, margin: "28px 0 8px" }, title: { color: "#F4EAF0", fontFamily: "Georgia, serif", fontSize: 44, lineHeight: 1.1, margin: 0 }, deck: { color: "#CBBBD0", fontSize: 19, lineHeight: 1.6, margin: "18px 0 34px" }, article: { color: "#E6DAE6", fontSize: 17, lineHeight: 1.75 }, cta: { display: "inline-block", color: "#1A1220", background: "linear-gradient(100deg,#E9A06B,#D46A8B)", padding: "10px 14px", borderRadius: 9, fontSize: 14, fontWeight: 700, textDecoration: "none" } };
