import type { Metadata } from "next";
import { JsonLd } from "@/components/JsonLd";
import { absoluteUrl } from "@/lib/site";

const title = "Creative Photo Moments: What an Unlock Means";
const description = "A clear guide to companion photo moments, credit-based reveals, and ReverieTale's age-appropriate fictional-content standards.";
export const metadata: Metadata = { title, description, alternates: { canonical: "/blog/creative-photo-moments" }, openGraph: { type: "article", title, description, url: "/blog/creative-photo-moments" } };

export default function CreativePhotoMomentsPost() {
  return <main style={S.wrap}><JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: title, description, author: { "@type": "Organization", name: "ReverieTale" }, mainEntityOfPage: absoluteUrl("/blog/creative-photo-moments") }} /><a href="/blog" style={S.back}>Journal</a><p style={S.eyebrow}>Creative moments</p><h1 style={S.title}>{title}</h1><p style={S.deck}>A photo moment is a fictional snapshot from a character's day. The reveal is always optional, and the credit cost is shown before you choose it.</p><article style={S.article}><h2>What you are unlocking</h2><p>Photo moments are companion-led images that support the story or chat: a backstage rehearsal, a sketchbook on a cafe table, a tournament day, or a strange clue from the character's world. They are creative context, not a requirement to keep talking.</p><h2>Clear choice before credits are spent</h2><p>When a moment has a credit cost, ReverieTale shows the cost before the image is revealed. You can skip it, continue the conversation, or come back later. A reveal never changes your access to the character or their story.</p><h2>Fictional and age-appropriate by design</h2><p>Every companion is fictional, and ReverieTale is designed for a 13+ audience. We do not use real people, require personal photos, or support explicit content. The goal is to give a story a visual beat while keeping the experience clear and comfortable.</p><p><a href="/guidelines" style={S.cta}>Read community guidelines</a></p></article></main>;
}

const S: Record<string, React.CSSProperties> = { wrap: { maxWidth: 740, margin: "0 auto", padding: "54px 24px 88px" }, back: { color: "#E9A06B", fontSize: 13.5, fontWeight: 700, textDecoration: "none" }, eyebrow: { color: "#E9A06B", fontSize: 12, letterSpacing: ".18em", textTransform: "uppercase", fontWeight: 700, margin: "28px 0 8px" }, title: { color: "#F4EAF0", fontFamily: "Georgia, serif", fontSize: 44, lineHeight: 1.1, margin: 0 }, deck: { color: "#CBBBD0", fontSize: 19, lineHeight: 1.6, margin: "18px 0 34px" }, article: { color: "#E6DAE6", fontSize: 17, lineHeight: 1.75 }, cta: { display: "inline-block", color: "#1A1220", background: "linear-gradient(100deg,#E9A06B,#D46A8B)", padding: "10px 14px", borderRadius: 9, fontSize: 14, fontWeight: 700, textDecoration: "none" } };
