import { LegalLayout, Section, S } from "@/components/LegalLayout";
import { OPERATOR_NAME, SUPPORT_EMAIL } from "@/lib/legal";

export const metadata = { title: "18 U.S.C. 2257 Exemption" };

export default function Exemption2257Page() {
  return (
    <LegalLayout eyebrow="Legal" title="18 U.S.C. § 2257 Exemption">
      <Section title="No real people are depicted">
        <p style={S.p}>
          {OPERATOR_NAME} is a purely AI-generated content platform. No real individuals are photographed, filmed, or otherwise
          depicted in any content created on or through the service. Every companion portrait, and every piece of story or chat
          content, is synthetic — generated by AI models from a text description, not from an actual person.
        </p>
        <p style={S.p}>
          Because no content on {OPERATOR_NAME} involves the actual sexually explicit conduct of a real person, the record-keeping
          and labeling requirements of 18 U.S.C. § 2257 and 2257A do not apply to {OPERATOR_NAME}.
        </p>
      </Section>
      <Section title="Contact">
        <p style={S.p}>
          Questions about this exemption can be sent to <a href={`mailto:${SUPPORT_EMAIL}`} style={S.link}>{SUPPORT_EMAIL}</a>.
        </p>
      </Section>
    </LegalLayout>
  );
}
